services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
     - "27057:27017" #primer numero, puerto no utilizado
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
     - mongo_data:/data/db
    networks:
     - mongo_network

volumes:
  mongo_data:

networks:
 mongo_network:
  driver: bridge